"""add user type

Revision ID: 4509b4fd34b6
Revises: 253f25058eca
Create Date: 2026-02-26 15:11:25.979948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4509b4fd34b6'
down_revision: Union[str, Sequence[str], None] = '253f25058eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Enum('ADMIN', 'USER', name='user_type_enum'), server_default=sa.text("'USER'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###
